server:
  port: 8330

logging:
  pattern:
    console: >
      %clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint}
      %clr(${LOG_LEVEL_PATTERN:-%5p})
      %clr(${PID:- }){magenta}
      %clr(---){faint}
      %clr([%15.15t]){faint}
      %clr([%X{mdc_trace_id}]){faint}
      %clr(%-40.40logger{39}){cyan}
      %clr(:){faint} %m${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
    file: >
     %d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}
     ${LOG_LEVEL_PATTERN:-%5p}
     ${PID:- } --- [%t] [%X{mdc_trace_id}] %-40.40logger{39}: %m${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

thread-pool-task-executor:
  core-pool-size: 24
  max-pool-size: 192
  queue-capacity: 2048