spring:
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:mysql://172.18.0.80:3306/anymock_opensource?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: service
    password: mysql1234TEST!
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 10
    host: 172.18.0.83
    port: 6379
    password: 911Test!